Add CFS model
blaylockbk/Herbie pull request #199
Opened 2023-05-29 21:31 UTC by blaylockbk

Adds a Herbie template for the NOAA Climate Forecast System (CFS)

Resolves #198 request.

The CFS model has lots of files associated with it, and thus the inputs for the Herbie template are kind of all over the place.

2025-01-02 14:51 UTC, MeasureSpace commented
Hello, any plan to merge this PR?

2025-01-02 21:48 UTC, MeasureSpace requested changes

2025-01-02 21:48 UTC, MeasureSpace commented on herbie/models/cfs.py
> +        PATH = f"/cfs.{self.date:%Y%m%d/%H}/6hrly_grib_{self.member:02d}/{self.product}{self.forecast:%Y%m%d%H}.{self.member:02d}.{self.date:%Y%m%d%H}.grb2"
remove `/` at the beginning

2025-01-02 21:48 UTC, MeasureSpace commented on herbie/models/cfs.py
> +            PATH = f"/cfs.{self.date:%Y%m%d/%H}/monthly_grib_{self.member:02d}/{self.product}.{self.member:02d}.{self.date:%Y%m%d%H}.{self.YYYYMM}.avrg.grib.{self.hour:02d}Z.grb2"
remove `/` at the beginning

2025-01-02 21:48 UTC, MeasureSpace commented on herbie/models/cfs.py
> +            PATH = f"/cfs.{self.date:%Y%m%d/%H}/monthly_grib_{self.member:02d}/{self.product}.{self.member:02d}.{self.date:%Y%m%d%H}.{self.YYYYMM}.avrg.grib.grb2"
remove `/` at the beginning

2025-01-03 04:36 UTC, blaylockbk commented
Thanks for the poke @MeasureSpace. After looking at this again, I remember why I didn't merge it...I am so unfamiliar with the CFS structure and didn't understand the naming convention to make the Herbie template easy to use. It would take some time to come up with a good template that allowed users to download all types of CFS files. 

I don't have that time now, but could do two things:
1. Merge this into the main branch, even though I feel like it's half baked (I added a warning that this CFS is an alpha capability).
2. Let you just use this branch if it works for you.

2025-01-03 19:29 UTC, MeasureSpace commented
Hi @blaylockbk, thanks a lot for the quick response. I tested the CFS code, and it works fine for me. Another useful component is the time series data from CFS (see below). Feel free to include it in your code. 

```python
class cfs_time_series:
    def template(self):
        self.DESCRIPTION = "Climate Forecast System; Time Series"
        self.DETAILS = {
            "NOMADS product description": "https://www.nco.ncep.noaa.gov/pmb/products/cfs/",
            "Amazon Open Data": "https://registry.opendata.aws/noaa-cfs/",
            "Microsoft Azure": "https://planetarycomputer.microsoft.com/dataset/storage/noaa-cfs",
        }
        # https://www.nco.ncep.noaa.gov/pmb/products/cfs/#DAILY
        self.PRODUCTS = {
            "wnd10m": "10 meter wind",
            "tmp2m": "2 meter temperature",
            "tmin": "Minimum Temperature 2 Meters Above",
            "tmax": "Maximum Temperature 2 Meters Above",
            "q2m": "2 meter specific humidity",
            "tcdcclm": "total cloud cover",
            "prate": "total precipitation rate",
            "weasd": " Water Equivalent of Accumulated Snow Depth",
            "soilt1": "Soil Temperature, 0-0.1 m Below Ground",
            "soilm1": "Soil Moisture Content, 0-0.1 m Below Ground",
            "pressfc": "surface pressure",
            "dswsfc": "shortwave radiation at the surface",
        }

        try:
            self.member
        except NameError:
            print(
                "'member' is not defined. Please set 'member=1` for monthly data for the 6, 12, and 18 UTC cycles, but may be 1, 2, 3, or 4 for the 0 UTC cycle."
            )

        PATH = f"cfs.{self.date:%Y%m%d/%H}/time_grib_{self.member:02d}/{self.product}.{self.member:02d}.{self.date:%Y%m%d%H}.daily.grb2"

        self.SOURCES = {
            "aws": f"https://noaa-cfs-pds.s3.amazonaws.com/{PATH}",
            "nomads": f"https://nomads.ncep.noaa.gov/pub/data/nccf/com/cfs/prod/{PATH}",
            # "azure": f"https://noaacfs.blob.core.windows.net/cfs/{PATH}"
        }

        self.IDX_SUFFIX = [".grb2.idx", ".idx", ".grib.idx"]
        self.LOCALFILE = f"{self.get_remoteFileName}"

```

2025-01-03 19:31 UTC, MeasureSpace approved these changes
Might want to check the CI failures and include the cfs_time_series model. Otherwise, LGTM.

2025-01-16 02:40 UTC, blaylockbk commented
Note: I turned off the use of pygrib to get the CF coordinate reference system because its failing the GitHub Action tests. I'll resolve that in another PR.

2025-01-16 02:40 UTC, merged